In [ ]:
!pip install fastbook

In [ ]:
import fastai
from fastai.tabular.all import *

import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Asteroid_Updated.csv (1).zip (Unzipped Files)/Asteroid_Updated.csv', low_memory=False)

In [ ]:
df = df.dropna(subset=["diameter", "rot_per"])
df = df[pd.to_numeric(df['diameter'], errors='coerce').notnull()]
df = df.interpolate()
df = df.round(decimals=5)

In [ ]:
cont_names = ['a', 'e', 'i', 'om', 'w', 'q', 'ad', 'per_y', 'data_arc', 'n_obs_used',
   'H', 'diameter', 'albedo', 'rot_per', 'moid','n', 'per', 'ma', 'GM', 'IR', 'BV', 'UB', 'G']
cat_names=['spec_B', 'spec_T', 'class']
df[cont_names]= df[cont_names].astype(float)
df = df[(cont_names + cat_names)]

In [ ]:
df.head()

,a,e,i,om,w,q,ad,per_y,data_arc,n_obs_used,H,diameter,albedo,rot_per,moid,n,per,ma,GM,IR,BV,UB,G,spec_B,spec_T,class
0,2.76917,0.07601,10.59407,80.30553,73.59769,2.55868,2.97965,4.60820,8822.0,1002.0,3.34,939.400,0.0900,9.07417,1.59478,0.21389,1683.14571,77.37210,62.6284,NaN,0.713,0.426,0.12,C,G,MBA
1,2.77247,0.23034,34.83623,173.08006,310.04886,2.13386,3.41107,4.61644,72318.0,8490.0,4.13,545.000,0.1010,7.81320,1.23324,0.21350,1686.15600,59.69913,14.3000,NaN,0.635,0.284,0.11,B,B,MBA
2,2.66915,0.25694,12.98892,169.85276,248.13863,1.98333,3.35497,4.36081,72684.0,7104.0,5.33,246.596,0.2140,7.21000,1.03454,0.22602,1592.78729,34.92502,16.0500,NaN,0.824,0.433,0.32,Sk,S,MBA
3,2.36142,0.08872,7.14177,103.81080,150.72854,2.15191,2.57093,3.62884,24288.0,9325.0,3.20,525.400,0.4228,5.34213,1.13948,0.27161,1325.43276,95.86194,17.8000,NaN,0.782,0.492,0.32,V,V,MBA
4,2.57425,0.19109,5.36699,141.57660,358.68761,2.08232,3.06617,4.13032,63507.0,2916.0,6.85,106.699,0.2740,16.80600,1.09589,0.23863,1508.60046,282.36629,16.0000,NaN,0.826,0.411,0.28,S,S,MBA

In [ ]:
dls = TabularDataLoaders.from_df(df, procs = [Categorify, FillMissing, Normalize], cat_names=['spec_B', 'spec_T', 'class'], 
                           cont_names=['a', 'e', 'i', 'om', 'w', 'q', 'ad', 'per_y', 'data_arc', 'n_obs_used', 'H', 'diameter', 
                                       'albedo', 'rot_per', 'moid','n', 'per', 'ma', 'GM', 'IR', 'BV', 'UB', 'G'],
                           y_names='diameter')

In [ ]:
learn = tabular_learner(dls, metrics=rmse)
learn.fit_one_cycle(3)